### PR TITLE
Getting bits of top domain in more efficient way

### PR DESCRIPTION
**Pull request by Artelov**
Reduced number of checks and code size

### CODE REVIEW

**Comment by arseny30** [comment]
https://github.com/TelegramMessenger/telemint/pull/53 did the same a bit earlier and probably a bit more optimal.

**Comment by loskutov** [comment]
In fact I guess making 1 loop iteration less is not a bad idea in terms of both readability and number of instructions executed

**Comment by Qverty** [comment]
@arseny30 
> #53 did the same a bit earlier and probably a bit more optimal.

Just looked. Yea, it's looks the same as #53, but it's still more effective in terms of performance and readability, as @loskutov mentioned.

**Comment by Artelov** [comment]
@arseny30 
> #53 did the same a bit earlier and probably a bit more optimal.
Just looked. Yea, it's looks the same as #53, but it's still more effective in terms of performance and readability, as @loskutov mentioned.

**Comment by Artelov** [comment]
@arseny30 
> #53 did the same a bit earlier and probably a bit more optimal.

Just looked. Yea, it's looks the same as #53, but it's still more effective in terms of performance and readability, as @loskutov mentioned.

**Pull request closed without merging**
